#!/bin/bash

IMAGE=/tmp/lock.png
SCREENSHOT="scrot $IMAGE"

$SCREENSHOT

convert $IMAGE -blur 0x5 $IMAGE 

i3lock -i $IMAGE
rm $IMAGE

# Small delay to prevent possible race conditions with suspend
sleep 1

exit 0
