#!/bin/sh

case "$1" in
    lock)
        $HOME/.config/i3/blurlock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        $HOME/.config/i3/blurlock && systemctl suspend
        ;;
    hibernate)
        $HOME/.config/i3/blurlock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "i3exit: missing or invalid argument!"
        echo "Available arguments: lock | logout | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
